---

- name: Provision a {{ application_name }} web server
  hosts: geonaut-dev
  become: yes
  become_user: root
  remote_user: "{{ server_user }}"
  vars:
    - update_apt_cache: yes
  vars_files:
    - env_vars/base.yml
    - env_vars/dev.yml
    - env_vars/prod.yml

  roles:
    # - base
    # - postgres
    # - nginx
    - app
    # - gunicorn
    # - certbot

