---

- name: Provision a {{ application_name }} web server
  hosts: geonaut-prod
  become: yes
  become_user: root
  remote_user: "{{ server_user }}"
  vars:
    - update_apt_cache: yes
  vars_files:
    - env_vars/base.yml
    - env_vars/prod.yml

  roles:
    # - base
    # - postgres
    # - app
    # - gunicorn
      - certbot
      - nginx


  # ansible-playbook prod.yml --skip-tags "development"

