---

- name: Check if django venv already exists
  stat: path=/{{ webroot }}/webapps/{{ django_venv_name }}
  register: django_test

- name: Install pip inside virtualenv
  pip:
    name: pip
    virtualenv: /{{ webroot }}/webapps/{{ django_venv_name }}
    virtualenv_python: python2.7
    state: latest
  when: not django_test.stat.exists
  become: True

- name: Install packages required by the Django app inside virtualenv
  pip: virtualenv=/{{ webroot }}/webapps/{{ django_venv_name }} requirements=/vagrant/django/requirements.txt
  when: not django_test.stat.exists

- name: Check if Django project folder already exists in virtualenv
  stat: path=/{{ webroot }}/webapps/{{ django_venv_name }}/{{ django_test_app_name}}
  register: django_test_subfolder

- name: Create django project directory
  file: path=/{{ webroot }}/webapps/{{ django_venv_name }}/{{ django_test_app_name}} state=directory
  when: not django_test_subfolder.stat.exists

- name: Install Django inside virtualenv using wrapper method
  pip: 
    name: django 
    virtualenv: /{{ webroot }}/webapps/{{ django_venv_name }}
  with_items:
    - django
  when: not django_test_subfolder.stat.exists
- template: src=django_venv_exec.j2 dest=/{{ webroot }}/webapps/{{ django_venv_name }}/exec mode=755
  when: not django_test_subfolder.stat.exists
- command: "/{{ webroot }}/webapps/{{ django_venv_name }}/exec django-admin.py startproject {{ django_test_app_name }} /{{ webroot }}/webapps/{{ django_venv_name }}/{{ django_test_app_name }}"
  when: not django_test_subfolder.stat.exists

- name: Overwrite settings.py
  template: src="django_settings.j2" dest="/{{ webroot }}/webapps/{{ django_venv_name }}/{{ django_test_app_name }}/{{ django_test_app_name }}/settings.py"
  tags:
    - template
  when: not django_test_subfolder.stat.exists

- name: Create migration file
  shell: /{{ webroot }}/webapps/{{ django_venv_name }}/bin/python manage.py makemigrations
  args:
    chdir: /{{ webroot }}/webapps/{{ django_venv_name }}/{{ django_test_app_name}}
  when: not django_test_subfolder.stat.exists

- name: Run migration file
  shell: /{{ webroot }}/webapps/{{ django_venv_name }}/bin/python manage.py migrate
  args:
    chdir: /{{ webroot }}/webapps/{{ django_venv_name }}/{{ django_test_app_name}}
  when: not django_test_subfolder.stat.exists

- name: Collect static content
  shell: /{{ webroot }}/webapps/{{ django_venv_name }}/bin/python manage.py collectstatic --no-input
  args:
    chdir: /{{ webroot }}/webapps/{{ django_venv_name }}/{{ django_test_app_name}}
  when: not django_test_subfolder.stat.exists

# Create a superuser 'python manage.py createsuperuser'
# run the local Django webserver with `python manage.py runserver 0.0.0.0:8000`