---

- name: Install Wagtail dependencies for Geonaut
  apt: name={{ item }} update_cache={{ update_apt_cache }} force=yes state=installed
  with_items:
    - g++ 
    - libjpeg62-dev 
    - zlib1g-dev
  tags: packages

- name: Ensure database is created
  become_user: postgres
  postgresql_db: name={{ db_name }}
                 encoding='UTF-8'
                 lc_collate='en_US.UTF-8'
                 lc_ctype='en_US.UTF-8'
                 template='template0'
                 state=present

- name: Ensure user has access to the database
  become_user: postgres
  postgresql_user: db={{ db_name }}
                   name={{ db_user }}
                   password={{ db_password }}
                   priv=ALL
                   state=present

# create a directory if it doesn't exist
- name: Check if wagtail venv already exists
  stat: path=/{{ webroot }}/webapps/{{ geonaut_venv_name }}
  register: geonaut_test

- name: Install pip inside virtualenv
  pip:
    name: pip
    virtualenv: /{{ webroot }}/webapps/{{ geonaut_venv_name }}
    virtualenv_python: python2.7
    state: latest
  when: not geonaut_test.stat.exists
  become: True

- name: Check if geonaut project folder already exists in virtualenv
  stat: path=/{{ webroot }}/webapps/{{ geonaut_venv_name }}/{{ geonaut_test_app_name}}
  register: geonaut_test_subfolder

- name: Clone project from GitHub
  git:
    repo: 'https://github.com/geonaut/geonaut-portfolio.git'
    dest: /{{ webroot }}/webapps/{{ geonaut_venv_name }}/geonaut
    version: master
  when: not geonaut_test_subfolder.stat.exists

- name: Install packages required by the geonaut app inside new project
  pip: virtualenv=/{{ webroot }}/webapps/{{ geonaut_venv_name }} requirements=/vagrant/webapps/geonaut_venv/geonaut/requirements.txt
  when: not geonaut_test_subfolder.stat.exists

- name: Create geonaut static directory
  file: path=/{{ webroot }}/webapps/{{ geonaut_venv_name }}/{{ geonaut_test_app_name}}/static state=directory
  when: not geonaut_test_subfolder.stat.exists

#   Won't work without settings fle

# - name: Run migration file
#   shell: /{{ webroot }}/webapps/{{ geonaut_venv_name }}/bin/python manage.py migrate
#   args:
#     chdir: /{{ webroot }}/webapps/{{ geonaut_venv_name }}/{{ geonaut_test_app_name}}
#   when: not geonaut_test_subfolder.stat.exists

# - name: Collect static files
#   shell: /{{ webroot }}/webapps/{{ geonaut_venv_name }}/bin/python manage.py collectstatic --no-input
#   args:
#     chdir: /{{ webroot }}/webapps/{{ geonaut_venv_name }}/{{ geonaut_test_app_name}}
#   when: not geonaut_test_subfolder.stat.exists
