---

- name: Create webroot directory
  file: path=/{{ webroot }}/webapps state=directory group=www-data
  # Become: True

# - include: global_installs.yml
# - include: django_new_project.yml
- include: wagtail_new_project.yml
