---

- name: Ensure bash, OpenSSL, and libssl are the latest versions
  apt: name={{ item }} update_cache={{ update_apt_cache }} state=latest
  with_items:
    - bash
    - openssl
    - libssl-dev
    - libssl-doc

- name: Install base packages
  apt: name={{ item }} update_cache={{ update_apt_cache }} force=yes state=installed
  with_items:
    - build-essential
    - acl
    - ntp
    - htop
    - git
    - libpq-dev
    - python-dev
    - python-pip
    - python3-pip
    - python-pycurl
    - ipython

- name: Upgrade pip
  pip: name=pip state=latest

- name: Add repository for Python 3.5 to the sources list
  apt_repository: repo='ppa:fkrull/deadsnakes'
                  update_cache={{ update_apt_cache }}
                  state=present

- name: Install Python 3.5 and related packages
  apt: name={{ item }} update_cache={{ update_apt_cache }} state=present
  with_items:
    - python3.5
    - python3.5-dev
    - python3-pip
    - ipython3

- name: Update bashrc to add geonaut aliases for Vagrant user
  lineinfile:
    dest=/home/vagrant/.bashrc
    line="{{ item.alias }} alias foo='bar'"
    regexp="^{{  item.regex  }}"
    owner=vagrant
    state=present
    insertafter=EOF
    create=True
  with_items:
    - { alias: "alias geonaut='cd /vagrant/webapps/geonaut_venv'", regex: 'alias geonaut'}
    - { alias: "alias geonautv='cd /vagrant/webapps/geonaut_venv;source bin/activate'", regex: 'alias geonautv'}
    - { alias: "alias geonautvp='cd /vagrant/webapps/geonaut_venv/geonaut;source ../bin/activate'", regex: 'alias geonautvp'}
  tags:
    - development
